#!/usr/bin/env bash

entrypoint=""

docker run --rm -it \
     --user $(id -u) \
     -v $(pwd):/app \
     -v ~/.composer:/composer \
     -e COMPOSER_HOME="/composer" \
     --env-file ./support/env/dev.env \
     composer/composer:php7 $@
