#!/usr/bin/env bash

docker run --rm -it \
     --user $(id -u) \
     -v $(pwd):/app \
     -v ~/.composer:/composer \
     -e COMPOSER_HOME="/composer" \
     --env-file ./support/env/dev.env \
     --entrypoint '/app/support/scripts/composer-entrypoint' \
     fesor/composer $@
