version: "2"

services:
    php:
        build: '.'
        depends_on:
            - database

    front:
        build: 'front'
        depends_on:
            - php

    database:
        build: 'support/database'
