version: "2"
services:
    php:
        volumes:
            - './../..:/srv'
        environment:
            - SYMFONY_ENV=dev

    nginx:
        ports:
            - 0.0.0.0:8080:80

    database:
        volumes:
            - dbdata:/var/lib/postgresql

volumes:
    dbdata:
        driver: local
