version: "2"

services:
    php:
        build:
            context: ./../../
            dockerfile: support/docker/php/Dockerfile
        image: $DOCKER_IMAGE_NAMESPACE-php
        environment:
            - SYMFONY_ENV=prod
            - SYMFONY__DATABASE__USER=${DB_USER}
            - SYMFONY__DATABASE__NAME=${DB_NAME}
            - SYMFONY__DATABASE__PASS=${DB_PASS}
            - SYMFONY__APP__SECRET=${APP_SECRET}

    nginx:
        build: nginx
        image: $DOCKER_IMAGE_NAMESPACE-nginx

    database:
        build: database
        image: $DOCKER_IMAGE_NAMESPACE-database
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASS}
            - PGPASSWORD=${DB_PASS}
