#!/usr/bin/env bash

compose="$(dirname $(dirname "$0"))/shortcuts/compose \
        -f docker-compose.yml -f support/docker-compose.test.yml"

# Run unit tests
$compose run --no-deps php bin/phpspec run && \

# Prepare app for reminding tests
$compose up -d database && \
$compose run --no-deps php bin/healthcheck 20 && \

# Run integrational/E2E tests
$compose run --no-deps php bin/behat

if [ $? -eq 0 ]
then
  echo "Tests passed!"
else
  echo "Tests failed!" >&2
fi

# Cleanup after tests
#$compose kill && \
#$compose rm -f -v
