#!/usr/bin/env bash

compose="docker-compose -p app_test -f docker-compose.yml -f support/docker-compose.test.yml"

# Run unit tests
$compose run --no-deps php bin/phpspec run && \

# Prepare app for reminding tests
$compose up -d database && \
$compose run --no-deps php bin/healthcheck 10

# Check migrations
$compose run --no-deps php bin/console migration:migrate -n
$compose run --no-deps php bin/console migration:validate

# Run integrational/E2E tests
$compose run --no-deps php bin/behat

if [ $? -eq 0 ]
then
  echo "Tests passed!"
else
  echo "Tests failed!" >&2
fi

# Cleanup after tests
$compose kill && \
$compose rm -f -v
