App\Domain\Task:
    type: entity
    table: tasks
    id:
        id:
            type: string
            generator: {strategy: NONE}

    fields:
        description:
            type: string
        status:
            type: string
        createdAt:
            type: datetime

    manyToOne:
        todoList:
            targetEntity: TodoList
