App\Domain\TodoList:
    type: entity
    table: todos
    id:
        id:
            type: integer
            generator: {strategy: AUTO}

    fields:
        name:
            type: string

    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: todoList
            cascade: ["persist", "merge"]

